name: demucs-app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.6
  - pip
  - black
  ##
  - ffmpeg>=4.2
  - libsndfile
  - pytorch>=1.8.1
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip:
    - algorithmia>=1.0.0,<2.0
    - six>=1.12.0
    - demucs
    - diffq>=0.1
    - julius>=0.2.3
    - lameenc>=1.2
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile
    - treetable>=0.2.3
